### ISSUE TITLE
关于开启SSR状态下，Wifi热点不可用的问题

### ISSUE THREAD

**Issue by authuir** [shadowsocksr/shadowsocksr-android#100]
之前在开启SSR状态下，直接开启wifi热点之后，其他设备虽然能连接上，而且DHCP也能获取到IP，但是手机上的网段192.168.43.0/24是没有路由连接上网的。
后来我手动通过手机终端添加了一条wlan0网卡到rmdata0网卡的路由(rmdata0应该是4g网络的网卡)，其他设备就可以连接外网了。
再后我添加wlan0网卡到tun0网卡的路由，(tun0应该是SSR这个app生成的虚拟网卡)，其他设备也没法通过ssr直接翻墙上网。
我注意到tun0网卡是一个p-t-p类型的网卡，不知道这样做是不是有问题。
后续版本是否可以加上wifi热点翻墙功能，谢谢。

**Comment by esdeathlove** [comment]
无计划添加。
