### ISSUE TITLE
请问能支持dns解析么，填域名不能启动啊

### ISSUE THREAD

**Issue by Wilson-G** [shadowsocksr/shadowsocksr-android#102]
rt

**Comment by breakwa11** [comment]
说明你用的DNS解析失败了，换个DNS呢

**Comment by Wilson-G** [comment]
不是啊，我换任何的地址，比如www.baidu.com都会提示服务器名无效

**Comment by breakwa11** [comment]
来个截图，你DNS到底怎么设置的

**Comment by Wilson-G** [comment]
![screenshot_2017-03-13-23-22-55](https://cloud.githubusercontent.com/assets/12825462/24069489/24ddcf78-0be4-11e7-89ef-8de72488fb5e.png)

**Comment by Wilson-G** [comment]
服务器那一栏，我用baidu域名代替了自己的服务器域名

**Comment by breakwa11** [comment]
拜托，那你的DNS呢

**Comment by Wilson-G** [comment]
China DNS
114.114.114.114:53,223.5.5.5:53
DNS
8.8.8.8:53

**Comment by Wilson-G** [comment]
这个应该是系统自动设置的

**Comment by Wilson-G** [comment]
不好意思，经你提醒我知道了，我是在未开数据未联网的情况下，先开启的ssr，所以没经过dns服务器，所以找不到ip。是我2了
