### ISSUE TITLE
关于安装时的问题

### ISSUE THREAD

**Issue by eatradish** [shadowsocksr/shadowsocksr-android#108]
安装时（在未装过 SSR 的环境）安装时会一直在安装界面，不会出现完成安装。
而更新安装则没有这个问题。
环境是 Nexus 5 / Lineage 14.1，在 Nexus 6P 原厂镜像下也有此问题

**Comment by fiercebead** [comment]
安装app的时候谷歌会联网检测什么东西吧，没翻墙连不上有时候安装过程就会很慢，你可以试试把wifi和流量都关了应该就快了。
在Windows上安装chrome的独立安装包有时候也这样，都tm独立安装包了还要联网，当然这也不能全怪谷歌，人家可能是为了让你用上最新版所以检测一下有没有新版，反正没翻墙的状态下断网安装最快。

**Comment by eatradish** [comment]
不对，只有 SSR 出现这个现象。
