### ISSUE TITLE
PAC文件导致的小问题

### ISSUE THREAD

**Issue by foreverBirds** [shadowsocksr/shadowsocksr-android#111]
本人正在使用的Shaodowsocks-Rss的程序版本为 4.1.4 （C#版本），当我更新PAC文件为绕过国内IP地址的时候，无法访问Youtube（只有这一个！！！），Chrome浏览器上反馈的错误为ERR_CONNECTION_CLOSED。但当我更新PAC文件为GFWList时，Telegram又需要把默认连接改成通过Socks5方式连接到本地代理服务器，速度上有明显的变化。

**Comment by breakwa11** [comment]
@foreverBirds 说明你那的DNS污染得不应该用那个PAC，你用C#版本为什么issue发在这里？

**Comment by foreverBirds** [comment]
那我改一下
