### ISSUE TITLE
SSR-Anrdoid路由设置为全局时，热点无法被连接

### ISSUE THREAD

**Issue by yshtcn** [shadowsocksr/shadowsocksr-android#115]
两台设备：
红米Note4，运行MIUI8.7.3.16，android版本6.0，运行最新版本SSR-Android，并开启热点。
iPhone 6 Plus一台，关闭局域网助理，连接上述红米Note4生成的热点生成的热点。

正确配置一个SSR服务器，不修改任何内容，路由为全局。打开热点，iPhone 6 Plus无法连上热点（显示无互联网连接），关掉热点正常连接。
路由设置调整为绕过中国大陆和局域网，可以正常连入热点上网，没有翻墙效果。

我遇到的问题是：
1，路由为全局时，可否用分应用代理的绕行模式把热点排除在影响之外。
2，路由为绕过中国大陆和局域网时，对热点的连入设备有无影响？（我感觉有时候部分连接有问题，要断开热点/关闭SSR才正常，但是没有作出可重复的实验）

**Comment by authuir** [comment]
这个问题我曾经发过一个issue，得到的回复是不会支持热点功能，我自己研究了一下，Root之后是可以自己通过设置iptables来达到这个效果的。
参看我写的这篇文章：
https://0v0.loan/index.php/archives/28/

**Comment by yshtcn** [comment]
@authuir 首先要谢谢您的热心，但是我想你有一点误会，我并不是需要SSR为热点提供服务。相反：我希望SSR与热点井水不犯河水。开启SSR时，热点仍如常工作。

**Comment by breakwa11** [comment]
@yshtcn 开启绕过局域网应该可以了

**Comment by yshtcn** [comment]
@breakwa11 我明白了，想要全局效果在android手机上体现又开启热点就用绕过局域网。3Q
至于SSR是不是还会影响热点我再试试。遇到了我再另外提问。
