### ISSUE TITLE
一加3t安卓7.1.1，有时候挂着ssr全局无法上网

### ISSUE THREAD

**Issue by zxd1997** [shadowsocksr/shadowsocksr-android#119]
有两次可能是离开了WiFi范围转4g之后，只要挂着ss就全局不能上网。关掉之后可以，但想挂ss要重启才行。不知道什么原因，发生问题的情况也不太清楚，只是有可能是WiFi切换4g时候出的问题。

**Comment by harnack** [comment]
我现在在小米note上用SSR也遇到这个问题，以前用影梭的时候并无此问题。

**Comment by esdeathlove** [comment]
现在的版本呢？
