### ISSUE TITLE
V3.3.6.2 无故退出

### ISSUE THREAD

**Issue by aimutu** [shadowsocksr/shadowsocksr-android#120]
moto xt1575, Android 6.0
使用过程中不知什么原因，经常退出。
没安装什么安全软件;
Google Play 里的那个 ss 能够正常使用。

**Comment by breakwa11** [comment]
@aimutu 添加到电源优化的白名单，不要优化它

**Comment by aimutu** [comment]
只安装了绿色守护和黑域，在这两个软件中都是放行的，在白名单内。

**Comment by aimutu** [comment]
被黑域自动加入了优化名单内
