### ISSUE TITLE
无法连接远程服务器:sendFd failed

### ISSUE THREAD

**Issue by hsiayuchih** [shadowsocksr/shadowsocksr-android#122]
一打开就提示“后台服务启动失败:无法连接远程服务器:sendFd failed'不知道啥情况，从旧版本更新到新版本也是一样的提示，还清除过数据重新配置一样不行，开始以为是SS服务器那边出问题了，但是后来发现电脑上的就没有这个问题...

**Comment by breakwa11** [comment]
@hsiayuchih 退回上一版本试试呢，你什么版本的系统

**Comment by hsiayuchih** [comment]
@breakwa11 最开始用的3.3.2，之前用的一直没事，直到昨天突然发现不行，于是今天就下了个最新版，结果发现还是不行，系统是7.0，之前一直用的好好的，就昨天突然发现不行的...

**Comment by mirifem** [comment]
检查手机管家之类的东西，看看是否被限权

**Comment by hsiayuchih** [comment]
解决了，重启手机解决
