### ISSUE TITLE
请问可以让ACL中定义的直连部分走国内DNS解析吗？

### ISSUE THREAD

**Issue by BROBIRD** [shadowsocksr/shadowsocksr-android#127]
尝试着制作了一个ACL，但是发现似乎所有域名无论是在代理列表还是直连列表都走了远程DNS解析？
此问题是否有解？是否可以改进一下？谢谢！
@esdeathlove @breakwa11 @Mygod @madeye

最明显的就是taobao.com（设置为直连），在自定义ACL的情况下网页端会出现跳转国际版的现象

**Comment by esdeathlove** [comment]
fixed
