### ISSUE TITLE
获取Root权限的方式问题

### ISSUE THREAD

**Issue by qiang-yu** [shadowsocksr/shadowsocksr-android#131]
我的手机安装了 SuperSU，程序申请获取 root 权限会提示，我点击授权就可以让程序获得 root 权限

但是 ssr 貌似没有这么一个 申请root 权限的过程， ssr 只是假设已经全局ROOT了，所以压根不申请root权限就直接上，结果就是 SuperSU 得不到任何申请提示，也就没法做授权， 所以 SSR 就没法正常工作

作者能加入 SSR启动申请ROOT 权限这个过程吗？ 

申请ROOT权限，得到授权，然后开始工作，这样比较合理吧

而不是假设ROM全局已经开了ROOT，压根不申请就直接用

**Comment by Love4Taylor** [comment]
很久之前用 SuperSU 的时候无问题 会提示要求 Root 授权 现在 用的 MagiskSU 依旧 没问题 会弹窗要求
 Root 授权

**Comment by qiang-yu** [comment]
多谢，那我换 MagiskSU 试试， SupuerSU 没有授权提示导致没法使用
