### ISSUE TITLE
在三星note3 N9009 安卓5.0上无法开机自启动连接

### ISSUE THREAD

**Issue by gang4399** [shadowsocksr/shadowsocksr-android#133]
开机无法自启动，确定无自启动干扰，后台服务查看已在运行，但没实现自动连接。

可能的干扰是系统开机首次连接VPN都会由“Android系统”提示许可。请指导处理，确保能开机直连上SSR

**Comment by gang43998** [comment]
再来。能自启很好啊

**Comment by gang4399** [comment]
3381开始已经OK了。谢谢
