### ISSUE TITLE
期待下个版本把arm64加回来

### ISSUE THREAD

**Issue by lcdbbs** [shadowsocksr/shadowsocksr-android#138]
起因:
https://github.com/shadowsocksr/shadowsocksr-android/issues/136#issuecomment-299089150
原来容易跑偏，新写一下

3.3.7.1两个版本都用不了了，3.3.5可以用。
对比了一下各版本区别，后面去掉了arm64，是不是这个原因。
我的S7是三星自家的64位处理器Exynos 8890
期待后面版本能把arm64找回来.

## 我也不能确定是不是arm64的问题,期待大神解决

**Comment by esdeathlove** [comment]
openssl那个就有arm64，所以不是这个问题。
