### ISSUE TITLE
3.4.0.3版本打开白屏。

### ISSUE THREAD

**Issue by miyouzi** [shadowsocksr/shadowsocksr-android#176]
Android 6.0.1 。
打开后程序无响应，一片空白。
已尝试卸载重装，未能解决。

**Comment by breakwa11** [comment]
@miyouzi 是不是有supersu，先打开

**Comment by miyouzi** [comment]
@breakwa11 已解决，原因是OTA升级完后supersu丢失了，现安装授权后可用。
另外发现第一次使用“扫描二维码”的时候调用了中国银行APP（？？抽风了？），再次使用的使用的时候提示 “没有安装符合zxing标准的扫描器” ，过往版本是可以直接扫描的，为什么这个版本需要这个依赖呢？

**Comment by breakwa11** [comment]
内置的有修不好的问题，就调用外置的
