### ISSUE TITLE
Feature settings 各Profile之间非独立设置而变成了共享设置

### ISSUE THREAD

**Issue by HarryLin2** [shadowsocksr/shadowsocksr-android#195]
即修改一个profile为bypass lan，所有profile跟着变

**Comment by breakwa11** [comment]
This is expected

**Comment by HarryLin2** [comment]
Well, it is not in the original shadowsocks. Did you change the behavior on purpose?

**Comment by hyxxsfwy** [comment]
路由设置全局生效的设定不合理啊。比如，有的节点支持 UDP 转发，有的不支持；有的节点支持 IPV6，有的不支持；有的节点是用来翻回国的，有的是用来连学校内网的……根本没法用统一的路由配置呀。
允许配置一个全局默认路由规则，然后每个服务器也可以单独修改路由设置，私以为这才是比较合理的设计。
