### ISSUE TITLE
有一个站，pc客户端能使用，android不能使用

### ISSUE THREAD

**Issue by duebbin** [shadowsocksr/shadowsocksr-android#201]
地址如下：ssr://dXMwMS5nb2FnZW50c3MuY2M6MTAzNDI6YXV0aF9zaGExX3YyOnJjNC1tZDU6dGxzMS4yX3RpY2tldF9hdXRoOmFtZDNNVGMwTmcvP29iZnNwYXJhbT0mcmVtYXJrcz1aMjloWjJWdWRITnpNUSZncm91cD1aMjloWjJWdWRITno

android没看到任何回包

**Comment by breakwa11** [comment]
@duebbin 所以非要用已经删除的协议吗

**Comment by duebbin** [comment]
@breakwa11 感谢大神回复，服务器不是我的，不知道还有废弃的协议这么一说，我后面自己搭个梯子吧，谢谢。
