### ISSUE TITLE
3.2.7.10无法使用UDP转发

### ISSUE THREAD

**Issue by NigelSong** [shadowsocksr/shadowsocksr-android#41]
在上一版本中UDP转发工作正常，升级到3.2.7.10后网页无法正常打开，用应用内的“检查网络连接”提示“Can't resolve hostname”

**Comment by glzjin** [comment]
@NigelSong 上一版本是？

**Comment by didila** [comment]
这状况很常见，就连记录上用8.8.8.8:53解析google.com都会出现Can't resolve hostname
ssr_3.2.7.2
ssr_3.2.7.8
ssr_3.2.7.10
这三个版本都会有
电脑板不会出现这个问题

**Comment by glzjin** [comment]
@didila 不好意思 你用的是 Android 还有你用原版测试过有问题吗 还有没事别开UDP转发 没多大用

**Comment by NigelSong** [comment]
@glzjin
上一版本为3.2.7.2

**Comment by didila** [comment]
@glzjin 了解了

**Comment by 1107470624** [comment]
下载源码导入到AS当中 不能进行编译 如何解决

**Comment by qhfls** [comment]
如果udp转发没多大用的话，怎么在android上防范DNS污染呢？

**Comment by glzjin** [comment]
@qhfls 最新版 你不用管=、=敏感域名会走tcp过ss远程解析

**Comment by qhfls** [comment]
@glzjin 是因为最新版内置了chinaDNS的原因吗？
