### ISSUE TITLE
自制二维码无法扫描

### ISSUE THREAD

**Issue by didila** [shadowsocksr/shadowsocksr-android#43]
这有两张二维码，内容为
ssr://MTIzLjEyMy4xMjMuMTIzOjQ1NjphdXRoX2FlczEyOF9zaGExOmNoYWNoYTIwLWlldGY6dGxzMS4yX3RpY2tldF9hdXRoOk56ZzUvP29iZnNwYXJhbT0mcmVtYXJrcz01cHlKNXBXSTVwbUM2WmFUNzd5YU1qQXhOLVc1dERBMzVweUlNVFRtbDZVZ01UQTZNems2TlRrJnVvdD0x
一张是由SSR C# 3.9.6.2生成，一张是利用PHP生成
但是PHP生成的二维码却无法在安卓版3.2.7.10扫描，在SSR C# 3.9.6.2可以扫描
制作二维码在安卓版扫描有什么该注意的吗？？？

![q5](https://cloud.githubusercontent.com/assets/4469206/20255215/be81b3a4-aa75-11e6-988f-94ea8dc02bc8.png)
![ssr](https://cloud.githubusercontent.com/assets/4469206/20255216/be87eb02-aa75-11e6-96fc-45cafebb6cbc.jpg)

**Comment by breakwa11** [comment]
不知道，用C#客户端扫的话结果倒是一样的
