### ISSUE TITLE
希望添加KCPTUN功能

### ISSUE THREAD

**Issue by xiaobailong24** [shadowsocksr/shadowsocksr-android#45]
官方Shadowsocks已支持KCPTUN，希望SSR增加对KCPTUN的支持。谢谢

**Comment by glzjin** [comment]
@xiaobailong24 不可能

**Comment by xiaobailong24** [comment]
为什么哪

**Comment by alechy** [comment]
@xiaobailong24 https://github.com/kaneawk/shadowsocksr-android 这里有一个.

**Comment by liaobin** [comment]
加了kcp那混淆就没作用了

**Comment by dragonrabbit** [comment]
我也想知道原因

**Comment by breakwa11** [comment]
https://github.com/shadowsocks/shadowsocks-android/commit/2798eddaa78fee94bdb87ef6da392ad05fe8d1d0
即将删除

**Comment by keytouch** [comment]
kcp用于大流量只会恶化链路，
仅仅用于降低延迟是不错的。

**Comment by becapital** [comment]
强烈要求安卓支持：SSR混淆+KCP+安卓版
