### ISSUE TITLE
SSR链接解析存在问题

### ISSUE THREAD

**Issue by ZeroClover** [shadowsocksr/shadowsocksr-android#51]
SSR链接要求BASE64为URL安全且不带padding，但是由于不同平台BASE64实现不一样，最终生成结果存在差异

观察到：

如果remask BASE64后有2个等号（padding），在去掉padding或者不去掉的情况下都能正常识别

如果remask BASE64 encode后不带padding或只有一个等号，那么remask就无法正常识别，表现为节点名称乱码

在Shadowrocket 、C#版中导入同样的SSR链接无此问题。C#版在生成BASE64时似乎会始终生成有2个padding的BASE64并删掉padding，Android SSR可以正常识别，但是比如php、Smarty、JS中的BASE64实现无法做到这样

**Comment by glzjin** [comment]
@ZeroClover 给下你说的几种情况的链接例子看看？

**Comment by ZeroClover** [comment]
`ssr://YXUtSVB2Ni5wcm8uY24yLm1vZToyMDAwMDphdXRoX3NoYTFfdjQ6Y2hhY2hhMjA6dGxzMS4yX3RpY2tldF9hdXRoOlNFMXpiMlowTVRNNU5FRlhWeU09Lz9vYmZzcGFyYW09YVc1MGJDNWhiR2w1ZFc0dVkyOXQmcmVtYXJrcz01cjZ6NXJTeUlFbFFkamJtanFYbGhhWG5ncmsmZ3JvdXA9Y21sNFEyeHZkV1FL`

`ssr://ZGUtSVB2Ni5wcm8uY24yLm1vZToyMDAwMDphdXRoX3NoYTFfdjQ6Y2hhY2hhMjA6dGxzMS4yX3RpY2tldF9hdXRoOlNFMXpiMlowTVRNNU5FRlhWeU09Lz9vYmZzcGFyYW09YVc1MGJDNWhiR2w1ZFc0dVkyOXQmcmVtYXJrcz01YjYzNVp1OUlFbFFkamJtanFYbGhhWG5ncmsmZ3JvdXA9Y21sNFEyeHZkV1FL`

**Comment by glzjin** [comment]
@ZeroClover 请问你使用的版本是？我这里测试解析并没有任何问题 可以截图你那边的吗

**Comment by ZeroClover** [comment]
方才发错链接，十分抱歉

`ssr://NDUuMjQ5LjkwLjE4OjExMDQxOmF1dGhfc2hhMV92NDpjaGFjaGEyMDp0bHMxLjJfdGlja2V0X2F1dGg6ZEdWemRBPT0vP29iZnNwYXJhbT0mcmVtYXJrcz02WitwNVp1OU1RPT0=
`

**Comment by glzjin** [comment]
@ZeroClover 你从哪里生成这个链接的？

**Comment by glzjin** [comment]
@ZeroClover 还有你说的最后一个问题，反倒是小火煎自动整理了，Android ssr 不会自动整理

**Comment by hkvsak** [comment]
类似这样的ssr配置android都导入失败，电脑上却没问题。。。ssr://NDcuODkuOS4yMDE6MTAwMDk6b3JpZ2luOnJjNC1tZDU6aHR0cF9zaW1wbGU6TWpReU9BPT0vP29iZnNwYXJhbT1kM2QzTG1KaGFXUjFMbU52YlE9PSZyZW1hcmtzPVcrYU9xT2lOa0YzcHBwbm11Szg9

**Comment by glzjin** [comment]
@hkvsak 你从哪生成这个链接地？

**Comment by hkvsak** [comment]
这里，https://www.mianvpn.com/

**Comment by glzjin** [comment]
@hkvsak 那你自己找他们去 要求他们按照正确格式生成

**Comment by hkvsak** [comment]
-_-||。。

**Comment by glzjin** [comment]
@hkvsak 不符合格式的链接，扫得出来是情分，扫不出来是本分

**Comment by hkvsak** [comment]
但是同样的链接，为什么电脑端就能解析？

**Comment by glzjin** [comment]
@hkvsak 别问我 反正我告诉你 这个链接不符合SSR的链接规范

**Comment by hkvsak** [comment]
-_-#。。OK

**Comment by lenovoy450** [comment]
@hkvsak 都不知道你脑子里装的啥，你找给你链接的人给你一个能读的app不就好了？
