### ISSUE TITLE
3.2.7.14为什么总是被提示安装包损坏无法安装啊？包括zeronet上下载的也是

### ISSUE THREAD

**Issue by Yamazaki-wu** [shadowsocksr/shadowsocksr-android#52]
3.2.7.14为什么总是被提示安装包损坏无法安装啊？包括zeronet上下载的也是

**Comment by chnt7305** [comment]
@Yamazaki-wu 看下你的安卓版本，5.0以下好像不支持了吧。

**Comment by breakwa11** [comment]
先删除旧的再安装

**Comment by youling257** [comment]
v3.2.7.10 之后的版本全部安装包已损坏，无法安装，卸载重装也是安装包已损坏 @breakwa11

**Comment by breakwa11** [comment]
下载后验证一下MD5看看，可能没有下载完整

**Comment by youling257** [comment]
就3M多的安装包，有可能下载不完整 ？

**Comment by youling257** [comment]
7.1.0系统能安装ssr 3.3.1，6.0.1系统不能

**Comment by Yamazaki-wu** [comment]
oppo手机，6.0.1，可以安装3.2.7.8，之后的版本一律提示安装包损坏。

2016-12-12 1:59 GMT+08:00 youling257 <notifications@github.com>:

**Comment by glzjin** [comment]
@Yamazaki-wu 截图 看看

**Comment by Yamazaki-wu** [comment]
![screenshot_2016-12-15-17-18-10-37](https://cloud.githubusercontent.com/assets/13083879/21218369/43bcffa0-c2eb-11e6-9117-eec501ec8aa6.png)
![screenshot_2016-12-15-17-18-00-79](https://cloud.githubusercontent.com/assets/13083879/21218371/43c37bf0-c2eb-11e6-9424-6515c7d4aadc.png)
![screenshot_2016-12-15-17-17-41-67](https://cloud.githubusercontent.com/assets/13083879/21218370/43bfeb98-c2eb-11e6-94e2-85514ac23c8d.png)

**Comment by Yamazaki-wu** [comment]
就算卸载老版本我也尝试过，无法安装。

**Comment by alechy** [comment]
我也遇到过,好像是签名的问题....

**Comment by Yamazaki-wu** [comment]
签名的问题就是显示安装包损坏？

**Comment by glzjin** [comment]
@Yamazaki-wu 我推荐您发一下 log cat 信息给我

**Comment by Yamazaki-wu** [comment]
可问题是从一开始到现在3.2.7.8就一直不需要自签名什么的，一样可以使用啊.

**Comment by Yamazaki-wu** [comment]
@glzjin 请问怎么获取log？以及要发哪个版本的给你？是已经安装成功的还是失败的？

**Comment by glzjin** [comment]
@Yamazaki-wu 失败的 adb logcat 安装过程的log输出给我

**Comment by q2785031** [comment]
同样也是oppo手机，3.2.7.8之后版本都无法安装，oppo r9s 系统6.0.1，难道是oppo手机有毒😂😂

**Comment by Yamazaki-wu** [comment]
@q2785031 我去……也是R9S，买之前纠结了很久，到底是821还是653或者625芯片，现在看来625的没有让我感觉很差，反而觉得网络连接速度、应用打开速度各种都比我以前的P8好多了。余大嘴果然不能太信了。

**Comment by Yamazaki-wu** [comment]
@glzjin 不知道怎么抓取log…… 望赐教。

**Comment by tommylwl** [comment]
我重新编译，在CENTOS 7.2 / MAC OS 10.11.6上， ARM架构的手机和平板安装都没问题，但在X86上就出现安装包已损坏。
但是你的安装包就没问题。我X86的安卓也是6.0. 
怎样办呀？能帮我一下吗？

**Comment by esdeathlove** [comment]
@Yamazaki-wu 能麻烦您给一下 adb logcat 抓取的日志给我吗？

**Comment by Yamazaki-wu** [comment]
@esdeathlove 不好意思，我不会抓。能麻烦告诉一下么？

**Comment by esdeathlove** [comment]
@Yamazaki-wu http://blog.csdn.net/xyz_lmn/article/details/7004710 辛苦了

**Comment by Yamazaki-wu** [comment]
@esdeathlove 先谢谢你了！我去试试看

**Comment by Yamazaki-wu** [comment]
@esdeathlove 不好意思，我没怎么看懂。以前自己刷过手机，大概知道ADB工具。请问工具下载完了需要输入什么命令啊？
前提手机通过数据线连接电脑，然后执行命令+参数？再然后选择安装程序，再然后导出日志？

**Comment by bt4wang** [comment]
SS 主分支已经修正这个问题，据说是因使用了一个不被colorOS支持的特性所致（似乎只有colorOS有这个问题，所以说其实应该是OPPO的锅），他们在3.4.2里取消了对着个特性的使用，于是SS主分支现在可以正常安装了。参见：
https://github.com/shadowsocks/shadowsocks-android/issues/1081

**Comment by Yamazaki-wu** [comment]
@bt4wang 谢谢你的答复！oppo论坛也有人提出相同的问题，那些工程师到现在还没解决。
play上貌似只有3.3.1？3.4.2去哪里下载啊？

**Comment by bt4wang** [comment]
@Yamazaki-wu 需要先加入beta测试，地址是 https://play.google.com/apps/testing/com.github.shadowsocks

**Comment by esdeathlove** [comment]
@Yamazaki-wu 这种东西最好是由厂商去解决，而不应该由 APP 开发者去妥协。

**Comment by Yamazaki-wu** [comment]
@bt4wang @esdeathlove 首先请在 Google Play 中下载该应用，然后您会收到包含测试版的相关更新。您可能需要先等几个小时，然后才会收到测试版更新。
然而play上的无法安装，依旧提示504错误，看来要么等正式版，要么等colorOS修复。
谢谢二位！如果要反馈给oppo工程师，怎么说呢，使用了一个不被colorOS支持的特性所致？

**Comment by esdeathlove** [comment]
@Yamazaki-wu 请您下载 https://github.com/shadowsocksr/shadowsocksr-android/releases/tag/v3.3.4.1 如果这个版本能安装，就是 android:extractNativeLibs 这个不被支持。

**Comment by bt4wang** [comment]
@Yamazaki-wu 你首先要装一个版本上去，才能进beta，默认会直接装最新的stable，当然会报错。
可以去SS的github上下最新的release。

**Comment by Yamazaki-wu** [comment]
@bt4wang 谢谢！但是我觉得这事就像@esdeathlove 说的那样并不应该由APP作者来解决。如果是多数系统都无法安装那就是APP的问题，可现在明显是某一款系统的问题。所以要告知系统开发人员去尽早处理。

**Comment by esdeathlove** [comment]
@Yamazaki-wu 对的，只有这样生态才能比较正常(注意是正常)地发展下去，如果各个厂商都这样改，那之后就没法玩了。

**Comment by Yamazaki-wu** [comment]
@esdeathlove 是啊，要是国内厂商都这么玩的话，我们这些需要FQ的岂不是都去刷原始版Android，或者不买国产手机了。

**Comment by esdeathlove** [comment]
@Yamazaki-wu 所以得由消费者和开发者一起，逼着他们不要瞎弄。

**Comment by bt4wang** [comment]
@Yamazaki-wu @esdeathlove 道理确实是这样的，但是嘛国内厂商的节操实在是……ColorOS通知授权的问题现在还没解决呢……手环推送动不动就给干掉了……

**Comment by esdeathlove** [comment]
@Yamazaki-wu 而不应该是遵守了规则的开发者去跟不遵守规则的厂商妥协。

**Comment by esdeathlove** [comment]
@bt4wang 所以，这种厂商的产品，就不要去买了。从你我他做起，动作再小都会有用。只要你去做了。

**Comment by bt4wang** [comment]
@esdeathlove 没有用的，翻墙电工才是小众……在人家看来这部分人本来就不是目标客户群。

**Comment by Yamazaki-wu** [comment]
http://bbs.coloros.com/thread-330692-2-1.html   我在后面跟帖回复了，然后看OPPO工程师怎么说了。

**Comment by esdeathlove** [comment]
@bt4wang 那就别买那种手机就好了，真的不能纵容他们瞎改，这次是这个客户端 APP 不能用，下次就保不齐是哪个 APP 就 OPPO 不能用了。

**Comment by Yamazaki-wu** [comment]
因为是小众群体，所以就可以理所当然的不管了？

**Comment by Yamazaki-wu** [comment]
如果执意如此，下次再也不买他家产品了。

**Comment by esdeathlove** [comment]
@Yamazaki-wu 小众不去争取自己的利益，下次受影响的可能就是大众了。

**Comment by Yamazaki-wu** [comment]
嗯，所以给他们提出问题了，就看改的结果如何。

**Comment by esdeathlove** [comment]
@Yamazaki-wu 辛苦了。

**Comment by bt4wang** [comment]
@Yamazaki-wu 确实如此，厂妹机不是白叫的……哎，这个机器的目标受众应该就是上上微信看看视频的没钱买iphone又稍微在乎点外形的妹子们……那个帖子快10天了。

**Comment by Yamazaki-wu** [comment]
@esdeathlove 我只是个搬砖的。要不是大大们搞出这些软件，还不是被成天洗脑。

**Comment by esdeathlove** [comment]
@bt4wang 问个题外话，当初你们买这台手机的动机是？

**Comment by bt4wang** [comment]
他们权限控制的太厉害，当然了这对于完全不会折腾的人是好事情……
@esdeathlove 不是我用的，我原来用的nexus5，然后给老婆换的，她用惯android不想换iOS。然后我接手淘汰的G3改成近AOSP系统用……

**Comment by Yamazaki-wu** [comment]
@esdeathlove 木有啥动机，正好要换机了，然后纠结了1周还是没决定。从朋友哪儿介绍跑去手机城，现场看过实体机然后就那么买下来了。625看来比我上一台麒麟925的P8好不少。

**Comment by bt4wang** [comment]
最近看我看youtube，她也想看才出来这一出。之前用的确实挺好，不需要折腾，不需要调校，续航能力不错，定位确实精准，市占率不是白来的。当然也有操蛋的，就是小众需求很难得到满足，在他们看来似乎手环党都是小众……

**Comment by Yamazaki-wu** [comment]
总体来说R9S还算是可以的，抛开我们所述的这些小众问题。再有就是个人觉得625不值2600这个价（官方要2799）

**Comment by Yamazaki-wu** [comment]
刚去下载测试了一下，SSR3.3.4.1可以安装了。
