### ISSUE TITLE
开启代理后应用连不上网

### ISSUE THREAD

**Issue by HaibaraLubov** [shadowsocksr/shadowsocksr-android#54]
开启代理后，使用浏览器可以浏览墙外的网页，但是譬如tumblr mbooru等一些其他应用却显示无连接，连墙内可以浏览的部分也显示无网络连接。

**Comment by esdeathlove** [comment]
如果仍有此情况，请发送你的详细设置上来。

**Comment by HaibaraLubov** [comment]
![20170317114631](https://cloud.githubusercontent.com/assets/24516868/24028115/8afab510-0b07-11e7-85e5-334a19ef12ae.jpg) 正常用一段时间后，部分应用就连不上网了，然后把连不上的应用卸载再重新安装一遍的话，就又能用代理了 但是浏览器是一直都能连
