### ISSUE TITLE
安卓4.4.2,SSR3.3.3频繁断线且无法重连的问题

### ISSUE THREAD

**Issue by DreamL** [shadowsocksr/shadowsocksr-android#63]
我这个可能是个别问题, nexus5、源生4.4.2系统, SSR3.3.3版本,
使用过程中经常是连上几分钟到十几分钟不等就断线,断线后重连就连不上了, 切换其他节点也都连不上,有的还报错,这时候关闭链接,关闭APP,重新打开,再进行连接就可以连上. 很困扰.希望给些建议解决此问题.

**Comment by esdeathlove** [comment]
@DreamL 可以麻烦您发一下具体的报错信息吗？

**Comment by DreamL** [comment]
@esdeathlove 
感谢回复.
好的, 现在有一会没报错了, 下次断开的时候, 我第一时间回复你.

**Comment by esdeathlove** [comment]
@DreamL 谢谢您。

**Comment by DreamL** [comment]
@esdeathlove 
hi 错误来了, 不过这次只看到两个, 还有2种错这次没看到.
这里是不能上图吗? 反正我是没找到按钮, 只好手打了.

error1.后台服务启动失败:无法链接远程服务器:Error running exec(). Command:[/data/data....
error2.后台服务启动失败:服务器名无效.

以上两个错误,是在忽然断开后,切换任何节点都会报,但不是固定哪一个错误.
出错同时使用PC尝试所有节点都可正常使用.
杀掉后台进程,重启APP,任何节点都可以正常连接和使用.

希望有帮助

**Comment by esdeathlove** [comment]
@DreamL 好的，明白了，您之后可以发一下 adb logcat 的日志给我吗？

**Comment by DreamL** [comment]
@esdeathlove 
印象中还有一个错误信息大概是:
nameDescriptor must not be null

**Comment by DreamL** [comment]
当然,可以, 但是,需要怎么操作, 麻烦说一下.

**Comment by esdeathlove** [comment]
@DreamL 还有您可以说一下您的协议，混淆方式，协议吗？

**Comment by DreamL** [comment]
协议:origin
协议参数:无
混淆方式:plain
加密方式:aes-256-cfb

**Comment by esdeathlove** [comment]
@DreamL adb logcat > bug.log 然后开始测试，测试完毕再用 ctrl+c 退出这个命令，bug.log 这个文件发我即可。

**Comment by esdeathlove** [comment]
@DreamL 可以发一下您的节点信息 SSR 链接吗，也就是分享的链接。

**Comment by DreamL** [comment]
实在不好意思, 我是第一天用安卓系统. adb logcat等我查查资料怎么用..
还有SSR链接 是什么? 就是我配置时候选择从剪切板导入的内容吗?

**Comment by esdeathlove** [comment]
@DreamL 对的

**Comment by DreamL** [comment]
能否QQ联系? 我QQ1633292

**Comment by esdeathlove** [comment]
@DreamL 不好意思 我不用 QQ

**Comment by DreamL** [comment]
那用什么即时沟通工具都可以.我的SS不是我自己的,发出来不太好.
另外我先配置一下adb, 等下次出错的时候,来记录日志

**Comment by esdeathlove** [comment]
@DreamL Telegram @glzjinmod 这个群，群里吼一嗓子就会有人找你了。

**Comment by DreamL** [comment]
好的,再出错就吼 2333

**Comment by DreamL** [comment]
算了 这问题不管了, 直接把系统升到6.0解决了.

**Comment by esdeathlove** [comment]
@DreamL 很抱歉没能及时解决你的问题，请问你手机上有没有装什么比较特殊的 APP 呢？另外之前 ROOT 了吗？
