### ISSUE TITLE
能不能加入自定义http混淆的uri

### ISSUE THREAD

**Issue by lnterface** [shadowsocksr/shadowsocksr-android#64]
RT

**Comment by esdeathlove** [comment]
@lnterface 咦，不是有吗？

**Comment by lnterface** [comment]
@esdeathlove 自定义uri喔，不是host哦，在host#后面加uri就会出现两个uri
能不能直接改第一个为自己想要的
![qq 20170110131945](https://cloud.githubusercontent.com/assets/19987129/21794712/ce048eb6-d737-11e6-914e-9fc8051e0cbd.jpg)

**Comment by breakwa11** [comment]
不可以

**Comment by lnterface** [comment]
那只能自己魔改一下代码自己编译自用咯
