### ISSUE TITLE
Please resume app update on Google Play

### ISSUE THREAD

**Issue by chnt7305** [shadowsocksr/shadowsocksr-android#66]
Have any plans for this area?
Thanks all developers.

**Comment by stardock** [comment]
Play 上部署要钱的

**Comment by acrossfreedom** [comment]
maybe i can do it .only $25 for a google play account

**Comment by acrossfreedom** [comment]
@breakwa11 ,why this app is not on google play? can I put it on google play?

**Comment by stardock** [comment]
@acrossfreedom  I think it's OK to place it on googe play for free download. But you need to get confirmation from breakwa11 if you want to sell it on play store.

**Comment by acrossfreedom** [comment]
@stardock @breakwa11 ,for the safety of my google play account,I need to know that if i put this app on google play,my account will be shutdown by google?(如果我把这个app放到google play，我的账号会不会被google封闭)

**Comment by breakwa11** [comment]
No, you can not put it on google play

**Comment by acrossfreedom** [comment]
@breakwa11  为什么不行啊？现在主页上面android版本是ss的，SSR没办法从google play下载，我不能传到google play的话，你总能传到google play 吧？

**Comment by stardock** [comment]
@acrossfreedom  放弃吧， 开发大拿 都说了不行， 有可能是基于安全(GFW)或者其它诸多方面的考量。

**Comment by chnt7305** [comment]
@breakwa11 Ok,I know.Thanks !
