### ISSUE TITLE
关于日语翻译

### ISSUE THREAD

**Issue by yyxida** [shadowsocksr/shadowsocksr-android#68]
用了了我的翻译好歹＠我一下嘛（＃滑稽）

需要的话，我可以补上ｓｓｒ与ｓｓ不同地方的翻译

**Comment by breakwa11** [comment]
骂他（＃滑稽），补补吧，新版本就补上你的名字（随便说句话都变成电影名了）

**Comment by esdeathlove** [comment]
@breakwa11 开心（＃滑稽）。

**Comment by esdeathlove** [comment]
@yyxida 感谢，在 about 页面里会加上。

**Comment by yyxida** [comment]
名字啥的无所谓啦，主要是闲的没事做，再说ｓｓｒ和ｓｓ文本区别不大，多干点活有利于日语学习（＃阴险）

**Comment by BROBIRD** [comment]
难道不应该是#(滑稽)吗……
