### ISSUE TITLE
无法扫描 SSR 二维码

### ISSUE THREAD

**Issue by jpcnmm** [shadowsocksr/shadowsocksr-android#69]
6.0系统, 试了最近几个版本都一样

**Comment by esdeathlove** [comment]
@jpcnmm 把二维码发到这里大家来试试

**Comment by jpcnmm** [comment]
![2017-01-12_103511](https://cloud.githubusercontent.com/assets/18543677/21874889/e484da02-d8b2-11e6-94b6-650a272a9f15.png)
纯测试用，地址什么的乱填的

**Comment by esdeathlove** [comment]
@jpcnmm 你的参数界面截图给我看看

**Comment by jpcnmm** [comment]
![2017-01-12_104400](https://cloud.githubusercontent.com/assets/18543677/21875056/0f7d2aec-d8b4-11e6-8d46-e3c4b43ad7b5.png)

**Comment by jpcnmm** [comment]
@esdeathlove  刚发现auth_sha1协议没了，换成auth_sha1_v2也是没用

**Comment by esdeathlove** [comment]
@jpcnmm 经过测试此二维码可以正常被 SSR Android 最新版 客户端扫描。

**Comment by jpcnmm** [comment]
噢噢，看来是我这边系统问题了。麻烦了

**Comment by esdeathlove** [comment]
@jpcnmm 请问你的版本是？(SSR Android 以及手机系统)

**Comment by jpcnmm** [comment]
华为MATE8, EMUI4.1,  android6.0
SSR Android 3.3.3.1
突然想到，这机子以前似乎就没扫过SSR的二维码，不知是系统问题还是跟其它APP冲突了

**Comment by breakwa11** [comment]
你原来不能扫描的二维码是哪里生成的

**Comment by jpcnmm** [comment]
@breakwa11 机子使用没多久，之前可能只是扫描普通SS的二维码，混淆协议都是手改，所以都没发现
现在一试，不管是自己生成的，还是其它ss站，都扫不了

**Comment by JasoGeorgeS** [comment]
华为P9 EMUI5.0 Android7.0一样的问题

**Comment by newcastlecy** [comment]
华为 EMUI 用SSR 扫码不清晰，其他扫码软件好像正常
三星6.0，小米miui8 灭有问题

**Comment by zdayx** [comment]
是华为EMUI的问题么？我还以为是不是双摄像头搞的调用摄像头问题导致无法对焦！我华为P9也是软件升到3.3以后的版本就无法正常扫码了！

**Comment by jpcnmm** [comment]
看来是EMUI通病了
