### ISSUE TITLE
HTTP post模式无法完全模拟 HTTP 1.1 协议，包头无法换行

### ISSUE THREAD

**Issue by lightpencil** [shadowsocksr/shadowsocksr-android#72]

**Comment by breakwa11** [comment]
@lightpencil 你确定你真的读了文档说明了？

**Comment by lightpencil** [comment]
根据ShadowsocksR协议插件文档，

> http_simple：并非完全按照http1.1标准实现，仅仅做了一个头部的GET请求和一个简单的回应，之后依然为原协议流。使用这个混淆后，已在部分地区观察到似乎欺骗了QoS的结果。对于这种混淆，它并非为了减少特征，相反的是提供一种强特征，试图欺骗GFW的协议检测。要注意的是应用范围变大以后因特征明显有可能会被封锁。此插件可以兼容原协议(需要在服务端配置为http_simple_compatible)，延迟与原协议几乎无异（在存在QoS的地区甚至可能更快），除了头部数据包外没有冗余数据包，客户端支持自定义参数，参数为http请求的host，例如设置为cloudfront.com伪装为云服务器请求，可以使用逗号分割多个host如a.com,b.net,c.org，这时会随机使用。注意，错误设置此参数可能导致连接被断开甚至IP被封锁，如不清楚如何设置那么请留空。服务端也支持自定义参数，意义为客户端仅能填写的参数列表，以逗号分割。
本插件的高级设置（C#版、python版及ssr-libev版均支持）：本插件可以自定义几乎完整的http header，其中前两行的GET和host不能修改，可自定义从第三行开始的内容。例子：
baidu.com#User-Agent: abc\nAccept: text/html\nConnection: keep-alive
这是填于混淆参数的内容，在#号前面的是上文所说的host，后面即为自定义header，所有的换行使用\n表示（写于配置文件时也可直接使用\n而不必写成\n，换行符亦会转换），如遇到需要使用单独的\号，可写为\\，最末尾不需要写\n，程序会自动加入连续的两个换行。

表示即使是完全按照例子，抓包后依然发现包头内容无法换行，但是”host“后换行成功。

**Comment by breakwa11** [comment]
@lightpencil 你的客户端版本是多少

**Comment by lightpencil** [comment]
在post模式下观察到了一样的结果，协议指出

> http_post：与http_simple绝大部分相同，区别是使用POST方式发送数据，符合http规范，欺骗性更好，但只有POST请求这种行为容易被统计分析出异常。此插件可以兼容http_simple，同时也可兼容原协议(需要在服务端配置为http_post_compatible)，参数设置等内容参见http_simple，密切注意如果使用自定义http header，请务必填写boundary。

然而这个boundary不清楚是什么

**Comment by lightpencil** [comment]
@breakwa11 3.3.3.1 谢谢破娃酱亲自回复

**Comment by lightpencil** [comment]
simple 倒无所谓， 我改一下issue

**Comment by lightpencil** [comment]
利用wireshark捕获

**Comment by breakwa11** [comment]
如果你用的是android版本，那么是不能用的，那个BUG还没修复，是已知的问题，如果是其它版本你更新到最新就可以用了

**Comment by lnterface** [comment]
@breakwa11 原来有这个bug，刚刚抓包试了一下果然不行
混淆参数写成baidu.com#User-Agent: abc\nAccept: *
无论是http_simple还是http_post都不行，抓包显示只有\r
附上抓包的截图，希望早日修复
![1](https://cloud.githubusercontent.com/assets/19987129/21954752/e27fc0c0-da95-11e6-886e-f57bcb4a7927.jpg)

**Comment by lightpencil** [comment]
@breakwa11 是Android版，现在确实bug存在，望早日修复。

**Comment by lightpencil** [comment]
@lnterface 不应该有 \r吧
根据测试\r成功转义了啊
\n无效

**Comment by lnterface** [comment]
@lightpencil  \r是程序本身设定自动加的，我不是说了吗，混淆参数我只是加了\n
就是这样
> baidu.com#User-Agent: abc\nAccept: *

**Comment by lnterface** [comment]
@lightpencil @breakwa11 刚刚试了一下，可以正常了，不过不是只是\n，要用\\n
最终这样写就能正常模拟了

> baidu.com#User-Agent: abc\\nAccept: *

**Comment by lightpencil** [comment]
感谢 @lnterface ，测试成功通过，该issue已经解决。协议插件文档需要更新。以及关于单\表示问题，如果换行用了\\r，\岂不是要用\\\\咯。（不过\用的很少）

**Comment by breakwa11** [comment]
请等待新版本release，已经解决了这个问题

**Comment by lightpencil** [comment]
@breakwa11 也就是说下一个版本\n可以正常使用咯

**Comment by esdeathlove** [comment]
@lightpencil https://github.com/shadowsocksr/shadowsocksr-android/releases/tag/v3.3.4

**Comment by lightpencil** [comment]
@esdeathlove  哥们太速度了666给个赞
