### ISSUE TITLE
全局模式下，可否将DNS解析交由服务器端完成？

### ISSUE THREAD

**Issue by liufanl** [shadowsocksr/shadowsocksr-android#74]
用的SSR Android3.3.3.1 ，开全局模式连接自己的路由器SSR服务端，China Dns 用的默认114和223，用测速大师测试DNS解析大概在500ms左右，有的时候甚至更长。因为本地DNS速度较快但是不支持TCP查询，所以要开启UDP转发，这种设置下，速度明显变快，但是不能防DNS污染。

因为路由器已经做了DNS防污染，可否增加设置，将手机端的DNS解析全部交给路由器SSR服务端完成？？

**Comment by esdeathlove** [comment]
@liufanl 全部填成自己路由器 IP 试试

**Comment by liufanl** [comment]
@esdeathlove  路由器的IP是动态的，现在是通过域名访问，DNS服务器可以设置为域名吗？而且这种方式需要开放路由器53端口，会不会被GFW扫到，造成污染？

**Comment by esdeathlove** [comment]
@liufanl 填内网IP:53

**Comment by liufanl** [comment]
@esdeathlove 设置为路由内网IP后不开UDP转发不能解析。路由器用的是dnsmasq，在路由器上用dig www.baidu.com +tcp能解析。。
