### ISSUE TITLE
如何配置怎么才能让混淆协议auth_aes128_md5能正常使用？

### ISSUE THREAD

**Issue by breakings** [shadowsocksr/shadowsocksr-android#83]
{
   "server":"0.0.0.0",
    "server_ipv6":"::",
    "local_address":"127.0.0.1",
    "local_port":1080,
    "port_password":{
        "port1":{"protocol":"auth_sha1", "password":"123456", "obfs":"http_simple", "obfs_param":""},
        "port2":{"protocol":"origin", "password":"123456"},
        "port3":{"protocol":"auth_sha1_v2", "password":"123456","obfs":"http_simple", "obfs_param":""},
        "port4":{"protocol":"auth_sha1_v4", "password":"123456","obfs":"http_simple", "obfs_param":""},
		"port5":{"protocol":"auth_aes128_md5", "password":"123456","obfs":"http_simple", "obfs_param":""}
     },
    "timeout":300,
    "method":"aes-256-cfb",
    "protocol": "auth_sha1_compatible",
    "protocol_param": "",
    "obfs": "http_simple_compatible",
    "obfs_param": "",
    "redirect": "",
    "dns_ipv6": false,
    "fast_open": false,
    "workers": 1
}

前面四个端口都正常，只有port5无法使用，是不是和 "protocol": "auth_sha1_compatible"有关？

**Comment by breakwa11** [comment]
无法使用到底是如何“无法使用”？log呢？发issue前的文字你到底读了没有
