### ISSUE TITLE
安卓最新SSR客户端3.3.4.5现在无法连接服务器并正常使用

### ISSUE THREAD

**Issue by zletpm** [shadowsocksr/shadowsocksr-android#87]
我使用的安卓ssr版本是3.3.4.5，起初能正常使用。前天服务端IP被封了，后来我更改服务端IP后，电脑能正常翻墙，但是手机就一直无法翻出。电脑和手机在同一个Wi-Fi下，电脑和手机ssr的配置相同，但是手机ssr连接后就是翻不出去。

**Comment by zletpm** [comment]
运营商是湖南联通。之前手机ssr一直比电脑快，电脑大部分时间是70-120KB/s，手机是1MB/s。直到某一天手机突然连不上服务器，后来发现服务器IP被封了。
现在我用新IP重建了ssr服务器，电脑能连上并正常使用，但是安卓手机端在正确设置的情况下依然无法连接服务器并正常使用

**Comment by breakwa11** [comment]
但我连你配置是什么都不知道

**Comment by zletpm** [comment]
需要提供什么信息？breakwa11

**Comment by zletpm** [comment]
手机ssr客户端配置如下

2017年2月9日 12:54，"破娃酱" <notifications@github.com>写道：
