### ISSUE TITLE
我的电池快爆炸了！

### ISSUE THREAD

**Issue by qiuzi** [shadowsocksr/shadowsocksr-android#88]
用了10分钟手机CPU和天线位置温度过高，恐怕电池因此爆炸。
请求优化功耗方面

**Comment by jeonhei** [comment]
确实耗电有问题 无论是选择自动翻还是分应用全局翻墙都这样

**Comment by alesky** [comment]
ssr的耗电确实可怕
我这oneplus 3t系统显示计算出的ssr耗电900mah

**Comment by kmahyyg** [comment]
ssr耗电太严重，仅次于"Lineage OS 系统".

xiaomi-ido-7.1.1-NOF26W userdebug kernel 3.10.49

请求优化@glzjin

**Comment by kmahyyg** [comment]
https://github.com/shadowsocks/shadowsocks-android/blob/master/.github/faq.md#why-does-shadowsocks-consume-so-much-battery-on-android-50

**Comment by qiuzi** [comment]
@kmahyyg  no no no 
In the wifi environment, the normal use of mobile phone Google Play service or other APP will not heat up
Just start shadowsocks-android the temperature rises rapidly

**Comment by kmahyyg** [comment]
So please change your title thanks. you have to show them your software
version and also your system version so they can help you solve the problem

2017年3月3日 13:04，"qiuzi" <notifications@github.com>写道：

**Comment by qiuzi** [comment]
你说怎么改 我按你的写

2017年3月3日星期五，kmahyyg <notifications@github.com> 写道：

**Comment by kmahyyg** [comment]
以我的机型为例：

Title: SSR 3.3.5 LineageOS 14.1-170301 耗电极端异常，请优化

Description:

SSR 3.3.5
LineageOS 14.1 Official Build 20170301
Android 7.1.1_r21 Gapps 20170228
小米-红米3(ido)

电池优化选项保持默认，但耗电异常，在其他应用耗电合理的情况下，电池曲线基本与水平轴呈60度夹角。耗电极快，已使用补丁版黑域阻止运行部分gapps套件，国产毒瘤淘宝等已放入冰箱冻结。使用ssr(vpn模式)并用chrome
stable(google play latest version)
单标签正常访问常规图文网页时基本cpu温度维持在45度，耗电约3min/1%，已查阅FAQ，请优化。

@esdeathlove

使用混淆auth-aes128-md5配合tls1.2，加密为chacha20-ietf



2017年3月3日 20:37，"qiuzi" <notifications@github.com>写道：

**Comment by esdeathlove** [comment]
http://www.jianshu.com/p/75952a2f0594

如果你仍然觉得电量统计那里不好看，我建议你直接卸载不要用了。

要是觉得手机烫的话。
1.尽可能控制后台app。
2.没了，就这样控制吧。

电池不耐用：
换手机。

**Comment by kmahyyg** [comment]
Thanks for reply.Its base is not the battery statistics in the Settings.But
the fact that I ensure that it really cost a lot of battery.Can I export
log or other things to check out the reason?

2017年3月4日 06:28，"Esdeath" <notifications@github.com>写道：

**Comment by esdeathlove** [comment]
你可以尝试第二点的测试方法。

**Comment by qiuzi** [comment]
看来是没办法优化且不想优化啰？ 这就让大家很尴尬了！

2017年3月4日星期六，Esdeath <notifications@github.com> 写道：

**Comment by kmahyyg** [comment]
@qiuzi Be respect,plz.
@esdeathlove I freeze all "you know"apps and also use prevent running to
reduce other apps' usage AS MUCH AS I CAN.

I followed the jianshu link , but I didn't find the tool he mentioned in
Google.My friends who installed much more apps than mine but running
Android 5.1.1,his SSR didn't cost that much battery.So, Please Optimize .

2017年3月4日 11:18，"qiuzi" <notifications@github.com>写道：

**Comment by esdeathlove** [comment]
并不是优不优化的问题，如你所见，在某台手机上很耗电，在某台手机上很省电，这是个相对的和整体的，所以，先自己想办法压住其他 app 吧。目前并没有什么好办法

**Comment by kmahyyg** [comment]
thx.I've no idea about this.Close Issue.thx.

2017年3月4日 11:53，"Esdeath" <notifications@github.com>写道：

并不是优不优化的问题，如你所见，在某台手机上很耗电，在某台手机上很省电，这是个相对的和整体的，所以，先自己想办法压住其他 app
吧。目前并没有什么好办法

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/shadowsocksr/shadowsocksr-android/issues/88#issuecomment-284124877>,
or mute the thread

**Comment by kmahyyg** [comment]
经过多方询问，高耗电及过热问题仅在7.+出现(最起码我身边是这样)，另外我看到，你的二进制文件/data/data/in.zhaoj.shadowskcr/ss-local居然是用的ss-libev?.......

有-V参数，可否单独添加一个参数用于输出日志到stdout或某个文件？我想log应该可以对这个issue有所帮助。

另外，这个世界没有无解的问题，肯定可以继续优化，只是可能要在rom上一起动手脚罢了。

**Comment by kmahyyg** [comment]
skcr -> socksr
