### ISSUE TITLE
ssr安卓上不能与adguard同时开启

### ISSUE THREAD

**Issue by johoney** [shadowsocksr/shadowsocksr-android#90]
如题，我在手机开启了adguard，http模式，但是依然无法与ssr共存，同时开启会导致无法访问互联网，或者速度巨慢，有时候可以访问一些网站但是很多网站访问不了，@breakwa11

**Comment by alexking99** [comment]
应该是你自己的问题 我也有用adguard http代理 可以同时开启

**Comment by johoney** [comment]
请问你用的什么规则，我用的是adbyby软件提供的规则，顺便询问下如何设置，是不是还要设计端口代理什么的？

**Comment by alexking99** [comment]
我是直接用内置规则easylist china
你先试试删了adbyby的规则 用内置规则easylist china    
代理端口都是默認就可以了
