### ISSUE TITLE
安装时的玄学问题

### ISSUE THREAD

**Issue by BakaChinatsu** [shadowsocksr/shadowsocksr-android#93]
SSR-Android版3.3.4.5以及部分老版本（不记得有哪个版本了...）下载后点安装会卡在安装中无法完成安装（复现需要删除SSR全新安装，建议备份好数据）

歪门邪道的解决方法：

方法1.将APK解压后重新用任意压缩软件压缩改名apk后再安装即可秒安 （这里我自己压缩改名后的apk大小和gh上的不一样 不知道会不会有可能问题出在压缩上 提及一下）

方法2.将安装有一段时间（我也不知道需要多久...）的安装界面后台，然后去再点一次apk会提示是否安装该应用的更新，点击继续即可秒安

环境 Nexus 5 7.1.1, Nexus 5X 7.1.1, LG G4 CM14 还有两个没统计到 我身边至少有4个人有这种现象

希望作者能解决下...

cc @Mirs332

**Comment by 007learner** [comment]
5X 7.11 同样有过此现象。

**Comment by esdeathlove** [comment]
无法复现，请提供更详细的描述。

**Comment by WarmColor** [comment]
相同问题，升级安装的时候一直显示在安装但是无法完成，点返回取消再次安装秒装

**Comment by xuan880** [comment]
谷歌的自动备份导致的问题，如果你安装的软件在谷歌上面进行了备份，那么下次全新安装的时候谷歌会自动在安装的时候进行恢复，如果安装软件的时候没有进行翻墙就会卡在恢复数据阶段，安装时记得使用代理。
