### ISSUE TITLE
建议ssr安卓端监听dhcp ip

### ISSUE THREAD

**Issue by impig33** [shadowsocksr/shadowsocksr-android#98]
经常在一些环境下，手机客户端是最方便的，比如在网吧，或者与人共享，但是安卓客户端现在监听的是127.0.0.1，建议下个版本可以直接监听网卡ip。

谢谢

**Comment by Love4Taylor** [comment]
然而这就有个问题 会被偷流量 除非再加个鉴权.....

**Comment by impig33** [comment]
偷什么流量? @Love4Taylor

**Comment by Love4Taylor** [comment]
@impig33 监听网卡IP 然后别人内网一扫 "嗯 这个人开了个好像代理的东西 用用看 哇 还能翻墙 来看几个视频" 然后你的流量就GG了

**Comment by Love4Taylor** [comment]
@impig33 原版里也曾经有过讨论
https://github.com/shadowsocks/shadowsocks-android/pull/1102

**Comment by impig33** [comment]
你想多了，端口也不是这么容易扫的，扫到了也不知道是什么端口，你也可以加密码啊

**Comment by Love4Taylor** [comment]
@impig33 我上面说了啊 "除非再加个鉴权" 另外 安全性 不是 "不容易” 怎么样 就能完全定论的

**Comment by impig33** [comment]
本来就有啊   右键 -> 选项设置  左下角不是有吗

**Comment by Love4Taylor** [comment]
@impig33 那是 Windows 客户端啊 而 Android 是靠 libev 版的 ss-local 来工作的啊....
